[2023-11-24 23:01:23,287: INFO: main: Welcome to our Custom log]
[2023-11-24 23:03:07,405: INFO: main: Welcome to our Custom log]
[2023-11-25 00:18:08,695: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 00:18:08,881: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 00:21:31,198: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 00:21:31,200: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 00:21:35,934: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 00:21:35,935: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 00:21:51,794: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 00:21:51,796: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 00:22:31,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 00:22:31,916: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 00:31:35,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 00:31:35,727: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 00:35:51,293: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 00:35:51,293: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 00:35:51,293: INFO: common: created directory at: artifacts]
[2023-11-25 00:35:51,293: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-25 00:35:51,306: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-25 00:36:01,636: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-25 01:01:29,519: INFO: main: >>>>>>> Stage  Data Ingestion Started <<<<<<<]
[2023-11-25 01:01:29,519: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 01:01:29,519: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 01:01:29,533: INFO: common: created directory at: artifacts]
[2023-11-25 01:01:29,533: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-25 01:01:29,533: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-25 01:01:37,086: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-25 01:01:38,211: INFO: main: >>>>>>> Stage  Data Ingestion Completed <<<<<<<]
[2023-11-25 01:40:36,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 01:40:36,422: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 01:40:36,431: INFO: common: created directory at: artifacts]
[2023-11-25 01:40:36,586: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-25 01:41:13,231: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-25 02:01:43,169: INFO: main: >>>>>>> Stage  Data Ingestion Started <<<<<<<]
[2023-11-25 02:01:43,184: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 02:01:43,184: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 02:01:43,184: INFO: common: created directory at: artifacts]
[2023-11-25 02:01:43,184: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-25 02:01:43,184: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-25 02:01:52,253: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-25 02:01:53,174: INFO: main: >>>>>>> Stage  Data Ingestion Completed <<<<<<<]
[2023-11-25 02:01:53,174: INFO: main: *******************]
[2023-11-25 02:01:53,174: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-25 02:01:53,174: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 02:01:53,174: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 02:01:53,174: INFO: common: created directory at: artifacts]
[2023-11-25 02:01:53,185: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-25 02:01:53,185: ERROR: main: local variable 'prepare_base_model' referenced before assignment]
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    prepare_base_model.main()
  File "c:\users\kaush\onedrive\desktop\avkalan.ai\my projects\kidney-disease-classification\src\CnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model = prepare_base_model(config=prepare_base_model_config)
UnboundLocalError: local variable 'prepare_base_model' referenced before assignment
[2023-11-25 02:05:53,641: INFO: main: >>>>>>> Stage  Data Ingestion Started <<<<<<<]
[2023-11-25 02:05:53,641: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 02:05:53,658: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 02:05:53,658: INFO: common: created directory at: artifacts]
[2023-11-25 02:05:53,658: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-25 02:05:53,658: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-25 02:06:04,020: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-25 02:06:05,406: INFO: main: >>>>>>> Stage  Data Ingestion Completed <<<<<<<]
[2023-11-25 02:06:05,413: INFO: main: *******************]
[2023-11-25 02:06:05,413: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-25 02:06:05,415: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-11-25 02:06:05,415: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-25 02:06:05,415: INFO: common: created directory at: artifacts]
[2023-11-25 02:06:05,421: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-25 02:06:06,098: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-25 02:06:06,488: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-01 18:01:35,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-01 18:01:35,459: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-01 18:01:35,467: INFO: common: created directory at: artifacts]
[2023-12-01 18:08:23,006: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-01 18:08:23,006: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-01 18:08:23,006: INFO: common: created directory at: artifacts]
[2023-12-01 18:08:23,013: INFO: common: created directory at: artifacts\training]
[2023-12-01 19:24:30,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-01 19:24:30,727: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-01 19:24:30,729: INFO: common: created directory at: artifacts]
[2023-12-01 19:24:30,730: INFO: common: created directory at: artifacts\training]
[2023-12-01 19:25:16,031: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-01 19:25:16,037: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-01 19:25:16,039: INFO: common: created directory at: artifacts]
[2023-12-01 19:25:16,041: INFO: common: created directory at: artifacts\training]
[2023-12-01 23:35:35,721: INFO: main: >>>>>>> Stage  Data Ingestion Started <<<<<<<]
[2023-12-01 23:35:35,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-01 23:35:35,721: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-01 23:35:35,737: INFO: common: created directory at: artifacts]
[2023-12-01 23:35:35,737: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-01 23:35:35,737: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-01 23:35:47,828: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-01 23:35:48,507: INFO: main: >>>>>>> Stage  Data Ingestion Completed <<<<<<<]
[2023-12-01 23:35:48,507: INFO: main: *******************]
[2023-12-01 23:35:48,507: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-01 23:35:48,507: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-01 23:35:48,507: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-01 23:35:48,507: INFO: common: created directory at: artifacts]
[2023-12-01 23:35:48,515: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-01 23:35:49,138: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-01 23:35:49,505: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-01 23:35:49,510: INFO: main: *******************]
[2023-12-01 23:35:49,510: INFO: main: >>>>>> stage Model training started <<<<<<]
[2023-12-01 23:35:49,512: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-01 23:35:49,518: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-01 23:35:49,520: INFO: common: created directory at: artifacts]
[2023-12-01 23:35:49,522: INFO: common: created directory at: artifacts\training]
[2023-12-02 00:11:07,241: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2023-12-02 08:27:45,907: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 08:27:45,919: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 08:27:45,954: INFO: common: created directory at: artifacts]
[2023-12-02 08:28:58,532: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 08:28:58,539: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 08:28:58,541: INFO: common: created directory at: artifacts]
[2023-12-02 08:31:25,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 08:31:25,945: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 08:31:25,953: INFO: common: created directory at: artifacts]
[2023-12-02 08:33:44,375: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 08:33:44,382: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 08:33:44,390: INFO: common: created directory at: artifacts]
[2023-12-02 09:02:14,930: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 09:02:14,939: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 09:02:14,942: INFO: common: created directory at: artifacts]
[2023-12-02 09:02:38,652: INFO: common: json file saved at: scores.json]
[2023-12-02 09:02:43,343: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-02 09:02:44,104: INFO: builder_impl: Assets written to: C:\Users\kaush\AppData\Local\Temp\tmpqluo2kjl\model\data\model\assets]
[2023-12-02 10:46:19,841: INFO: main: >>>>>>> Stage  Data Ingestion Started <<<<<<<]
[2023-12-02 10:46:19,860: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 10:46:19,860: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 10:46:19,860: INFO: common: created directory at: artifacts]
[2023-12-02 10:46:19,860: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-02 10:46:19,860: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-02 10:46:29,703: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-02 10:46:32,807: INFO: main: >>>>>>> Stage  Data Ingestion Completed <<<<<<<]
[2023-12-02 10:46:32,808: INFO: main: *******************]
[2023-12-02 10:46:32,810: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-02 10:46:32,810: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 10:46:32,824: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 10:46:32,827: INFO: common: created directory at: artifacts]
[2023-12-02 10:46:32,827: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-02 10:46:34,310: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-02 10:46:35,056: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-02 10:46:35,056: INFO: main: *******************]
[2023-12-02 10:46:35,056: INFO: main: >>>>>> stage Model training started <<<<<<]
[2023-12-02 10:46:35,056: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 10:46:35,073: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 10:46:35,077: INFO: common: created directory at: artifacts]
[2023-12-02 10:46:35,080: INFO: common: created directory at: artifacts\training]
[2023-12-02 10:49:32,368: ERROR: main: Graph execution error:

PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\Tumor\\Tumor- (997).jpg'
Traceback (most recent call last):

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\ops\script_ops.py", line 267, in __call__
    ret = func(*args)

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\data\ops\from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 902, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 1049, in generator_fn
    yield x[i]

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\Tumor\\Tumor- (997).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    prepare_base_model.main()
  File "c:\users\kaush\onedrive\desktop\avkalan.ai\my projects\kidney-disease-classification\src\CnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\kaush\onedrive\desktop\avkalan.ai\my projects\kidney-disease-classification\src\CnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\Tumor\\Tumor- (997).jpg'
Traceback (most recent call last):

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\ops\script_ops.py", line 267, in __call__
    ret = func(*args)

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\data\ops\from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 902, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\engine\data_adapter.py", line 1049, in generator_fn
    yield x[i]

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 116, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 370, in _get_batches_of_transformed_samples
    img = image_utils.load_img(

  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:

PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\kidney-ct-scan-image\\Tumor\\Tumor- (997).jpg'


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1463]
[2023-12-02 10:50:44,153: INFO: main: >>>>>>> Stage  Data Ingestion Started <<<<<<<]
[2023-12-02 10:50:44,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 10:50:44,153: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 10:50:44,153: INFO: common: created directory at: artifacts]
[2023-12-02 10:50:44,153: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-02 10:50:44,153: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-02 10:50:54,011: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-02 10:50:55,639: INFO: main: >>>>>>> Stage  Data Ingestion Completed <<<<<<<]
[2023-12-02 10:50:55,639: INFO: main: *******************]
[2023-12-02 10:50:55,639: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-02 10:50:55,639: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 10:50:55,657: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 10:50:55,659: INFO: common: created directory at: artifacts]
[2023-12-02 10:50:55,661: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-02 10:50:56,634: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-02 10:50:57,098: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-02 10:50:57,098: INFO: main: *******************]
[2023-12-02 10:50:57,098: INFO: main: >>>>>> stage Model training started <<<<<<]
[2023-12-02 10:50:57,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 10:50:57,112: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 10:50:57,114: INFO: common: created directory at: artifacts]
[2023-12-02 10:50:57,116: INFO: common: created directory at: artifacts\training]
[2023-12-02 11:07:19,124: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2023-12-02 11:07:19,126: INFO: main: *******************]
[2023-12-02 11:07:19,129: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2023-12-02 11:07:19,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:07:19,171: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:07:19,179: INFO: common: created directory at: artifacts]
[2023-12-02 11:08:28,393: INFO: common: json file saved at: scores.json]
[2023-12-02 11:08:28,424: INFO: common: json file saved at: scores.json]
[2023-12-02 11:08:34,490: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-02 11:08:36,258: INFO: builder_impl: Assets written to: C:\Users\kaush\AppData\Local\Temp\tmpfg0l_46e\model\data\model\assets]
[2023-12-02 11:10:17,834: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2023-12-02 11:19:59,713: INFO: main: >>>>>>> Stage  Data Ingestion Started <<<<<<<]
[2023-12-02 11:19:59,713: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:19:59,713: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:19:59,713: INFO: common: created directory at: artifacts]
[2023-12-02 11:19:59,724: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-02 11:19:59,726: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-02 11:20:08,113: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-02 11:20:10,488: INFO: main: >>>>>>> Stage  Data Ingestion Completed <<<<<<<]
[2023-12-02 11:20:10,489: INFO: main: *******************]
[2023-12-02 11:20:10,489: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-02 11:20:10,490: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:20:10,503: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:20:10,506: INFO: common: created directory at: artifacts]
[2023-12-02 11:20:10,508: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-02 11:20:12,022: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-02 11:20:13,041: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-02 11:20:13,041: INFO: main: *******************]
[2023-12-02 11:20:13,041: INFO: main: >>>>>> stage Model training started <<<<<<]
[2023-12-02 11:20:13,061: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:20:13,067: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:20:13,070: INFO: common: created directory at: artifacts]
[2023-12-02 11:20:13,073: INFO: common: created directory at: artifacts\training]
[2023-12-02 11:26:47,143: INFO: main: >>>>>> stage Model training completed <<<<<<

x==========x]
[2023-12-02 11:26:47,168: INFO: main: *******************]
[2023-12-02 11:26:47,168: INFO: main: >>>>>> stage Model Evaluation started <<<<<<]
[2023-12-02 11:26:47,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:26:47,189: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:26:47,201: INFO: common: created directory at: artifacts]
[2023-12-02 11:27:49,279: INFO: common: json file saved at: scores.json]
[2023-12-02 11:27:49,281: INFO: common: json file saved at: scores.json]
[2023-12-02 11:27:56,694: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-02 11:27:57,751: INFO: builder_impl: Assets written to: C:\Users\kaush\AppData\Local\Temp\tmpco_a4al4\model\data\model\assets]
[2023-12-02 11:29:38,874: INFO: main: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2023-12-02 11:30:08,993: INFO: stage_01_data_ingestion: >>>>>>> Stage  Data Ingestion Started <<<<<<<]
[2023-12-02 11:30:09,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:30:09,010: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:30:09,013: INFO: common: created directory at: artifacts]
[2023-12-02 11:30:09,019: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-02 11:30:09,022: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-02 11:30:30,563: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-02 11:30:32,886: INFO: stage_01_data_ingestion: >>>>>>> Stage  Data Ingestion Completed <<<<<<<]
[2023-12-02 11:31:27,215: INFO: stage_02_prepare_base_model: *******************]
[2023-12-02 11:31:27,215: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2023-12-02 11:31:27,222: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:31:27,222: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:31:27,222: INFO: common: created directory at: artifacts]
[2023-12-02 11:31:27,234: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-02 11:31:28,718: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-02 11:31:29,346: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-02 11:31:46,480: INFO: stage_03_model_training: *******************]
[2023-12-02 11:31:46,480: INFO: stage_03_model_training: >>>>>> stage Model training started <<<<<<]
[2023-12-02 11:31:46,495: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:31:46,496: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:31:46,507: INFO: common: created directory at: artifacts]
[2023-12-02 11:31:46,510: INFO: common: created directory at: artifacts\training]
[2023-12-02 11:38:13,360: INFO: stage_03_model_training: >>>>>> stage Model training completed <<<<<<

x==========x]
[2023-12-02 11:38:27,309: INFO: stage_04_model_evaluation_mlflow: *******************]
[2023-12-02 11:38:27,309: INFO: stage_04_model_evaluation_mlflow: >>>>>> stage Model Evaluation started <<<<<<]
[2023-12-02 11:38:27,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-02 11:38:27,324: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-02 11:38:27,327: INFO: common: created directory at: artifacts]
[2023-12-02 11:39:32,369: INFO: common: json file saved at: scores.json]
[2023-12-02 11:39:32,379: INFO: common: json file saved at: scores.json]
[2023-12-02 11:39:39,658: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-12-02 11:39:41,871: INFO: builder_impl: Assets written to: C:\Users\kaush\AppData\Local\Temp\tmp8m_e7wqa\model\data\model\assets]
[2023-12-02 11:41:42,150: INFO: stage_04_model_evaluation_mlflow: >>>>>> stage Model Evaluation completed <<<<<<

x==========x]
[2023-12-02 12:06:11,012: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.99.106:8080]
[2023-12-02 12:06:11,012: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-02 12:06:30,259: INFO: _internal: 127.0.0.1 - - [02/Dec/2023 12:06:30] "GET / HTTP/1.1" 200 -]
[2023-12-02 12:07:16,730: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\kaush\onedrive\desktop\avkalan.ai\my projects\kidney-disease-classification\src\CnnClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2023-12-02 12:07:16,878: INFO: _internal: 127.0.0.1 - - [02/Dec/2023 12:07:16] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-02 12:09:39,244: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.99.106:8080]
[2023-12-02 12:09:39,244: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-02 12:09:45,878: INFO: _internal: 127.0.0.1 - - [02/Dec/2023 12:09:45] "GET / HTTP/1.1" 200 -]
[2023-12-02 12:09:59,543: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\kaush\onedrive\desktop\avkalan.ai\my projects\kidney-disease-classification\src\CnnClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("artifacts", "model", "model.h5"))
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kaush\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\model\model.h5
[2023-12-02 12:09:59,562: INFO: _internal: 127.0.0.1 - - [02/Dec/2023 12:09:59] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-02 12:14:08,540: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.99.106:8080]
[2023-12-02 12:14:08,542: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-02 12:14:13,205: INFO: _internal: 127.0.0.1 - - [02/Dec/2023 12:14:13] "GET / HTTP/1.1" 200 -]
[2023-12-02 12:14:32,075: INFO: _internal: 127.0.0.1 - - [02/Dec/2023 12:14:32] "POST /predict HTTP/1.1" 200 -]
[2023-12-02 12:14:57,056: INFO: _internal: 127.0.0.1 - - [02/Dec/2023 12:14:57] "POST /predict HTTP/1.1" 200 -]
